export type Icons =
   | "add-user"
   | "delivery"
   | "growth"
   | "orders"
   | "plus"
   | "raw-material"
   | "remove"
   | "remove-user"
   | "stock"
   | "user"
   | "users-book"
   | "shopping-bag"
